name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  minify-js:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Auto Minify JS
      uses: nizarmah/auto-minify@v2.1
      with:
        directory: 'assets/js'
        
    - uses: actions/upload-artifact@v2
      with:
        name: minified-js
        path: assets/js/*.min.js
        
  minify-css:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Auto Minify CSS
      uses: nizarmah/auto-minify@v2.1
      with:
        directory: 'assets/css'    
        
    - uses: actions/upload-artifact@v2
      with:
        name: minified-css
        path: assets/css/*.min.css
  
  purge-css:
    needs: minify-css
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: minified-css
          path: assets/css/

      - name: PurgeCSS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -g purgecss
      - run: purgecss --css 'assets/css/*.min.css' --content '*.html' --output 'assets/css/'
      
      - uses: actions/upload-artifact@v2
        with:
          name: purged-css
          path: assets/css/*.min.css

  sitemap:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://note-thing.github.io/
        
    - uses: actions/upload-artifact@v2
      with:
        name: sitemap
        path: sitemap.xml
        
  commit:
    needs: [minify-js, purge-css, sitemap]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: sitemap
          path: ./
          
      - uses: actions/download-artifact@v2
        with:
          name: purged-css
          path: assets/css/
          
      - uses: actions/download-artifact@v2
        with:
          name: minified-js
          path: assets/js/

      - name: Auto committing new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: './'
          commit_message: "Github Action: newly generated files"
          branch: ${{ github.ref }}
